### ISSUE TITLE
Location errónea al crear un shop

### ISSUE THREAD

**Issue by npasserini** [arq2/app#13]
Cuando creo un shop me devuelve un header location, por ejemplo:  
`location: 'http://localhost:8080/api/v1/shops/5727db91008c5b2c1d888155'`

Sin embargo esa URL es incorrecta, en la versión correcta falta `arq2` en el path:
http://localhost:8080/arq2/api/v1/shops/5727db91008c5b2c1d888155

**Comment by ngarbezza** [comment]
@npasserini ya estamos trabajando en ello. La idea es borrar ese `/arq2` como root de nuestra api

**Comment by npasserini** [comment]
👍

**Comment by npasserini** [comment]
Fíjense que la documentación quedó desactualizada después de ese cambio.
