### ISSUE TITLE
Error al correr mvn package

### ISSUE THREAD

**Issue by npasserini** [arq2/app#7]
Les paso el trace del error que dio:

[error-trace.txt](https://github.com/arq2/app/files/235499/error-trace.txt)

**Comment by ngarbezza** [comment]
@npasserini ese error era de cuando usábamos Jetty y no estaba configurado correctamente. Ahora estamos usando otro server que se llama Undertow y el `mvn package` no debería tirar ningún error.

cc @rochiAmaya
